#!/bin/bash -ex

cd $(dirname $0)/..

mkdir -p results
pip install --no-cache-dir -r test-requirements.txt

if ! pytest harvester_e2e_tests -v -m "smoke" --html=results/api.html; then
  touch results/fail
fi
